name: Main Push

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Checkout badges branch
        uses: actions/checkout@v4
        with:
          ref: badges
          path: badges

      - name: Checkout Main Project
        uses: actions/checkout@v4
        with:
          path: main-project

      - name: Checkout gradle-kit
        uses: actions/checkout@v4
        with:
          repository: jonloucks/gradle-kit
          path: gradle-kit

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish gradle-kit locally
        working-directory: gradle-kit
        run: ./gradlew publishToMavenLocal
        env:
          PROJECT_WORKFLOW: 'utility'

      - name: Build Code Coverage and Source Documentation
        working-directory: main-project
        run: ./gradlew build jacocoTestReport javadoc
        env:
          PROJECT_WORKFLOW: 'main-pull-request'

      - name: Copy Code Coverage and Source Documentation
        working-directory: gh-pages
        run: |
          rm -rf docs/javadoc/
          mkdir -p docs/javadoc
          cp -r "${{ github.workspace }}/main-project/build/docs/javadoc/"* docs/javadoc/
          rm -rf gh-pages/docs/jacoco/
          mkdir -p docs/jacoco
          cp -r "${{ github.workspace }}/main-project/build/reports/jacoco/test/"* docs/jacoco/

      - name: Commit and Push gh-pages
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update Source Documentation'
          cwd: gh-pages

      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: main-project/build/reports/jacoco/test/html/

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          coverage-badge-filename: ${{ env.BRANCH_NAME }}-coverage.svg
          badges-directory: badges
          jacoco-csv-file: main-project/build/reports/jacoco/test/jacocoTestReport.csv
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Commit and Push the Badge
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update JaCoCo coverage badge'
          add: '*.svg'
          cwd: badges

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"